# Jupyter Book settings

title: Python Exercices
author: Thierry Parmentelat
logo: media/logo-python.svg

repository:
  url: https://github.com/flotpython/exos
  branch: main
  path_to_book: .

html:
  use_repository_button: yes
  use_edit_page_button: yes
  use_issues_button: yes

only_build_toc_files: true

exclude_patterns:
  # required to prevent endless deepening
  # of the build tree
  - "**/_build"
  - "**/.teacher/*"
  - "**/teacher/*"
  - "**/.ipynb_checkpoints"
  - "**/.pytest_cache"

execute:
  execute_notebooks: cache
  exclude_patterns:
    - "**/*-corrige*"
    - "**/.teacher/*"
    - "**/teacher/*"
    - "**/snake*.py"

parse:
  myst_enable_extensions:
    - html_image    # for raw <img> tags in markdown
    - dollarmath    # for mathjax
    - strikethrough

sphinx:
  config:
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py:percent
    html_show_copyright: false
    # not quite convincing but...
    html_extra_path:
      - media
      - lite
    jupyterlite_dir: .
  extra_extensions:
    - jupyterlite_sphinx
