# Jupyter Book settings

title: Python Exercices
author: Thierry Parmentelat
# this is tweaked by a sed command in ds/.readthedocs.yaml
logo: media/logo-exos-python.svg

# we want the corriges to build as well
# only_build_toc_files: true

exclude_patterns:
  # required to prevent endless deepening
  - "book-python/**/*"
  - "book-ds/**/*"
  # consider only filenames that start with an uppercase
  # there is something fishy here:
  # if we don't put the extension part, it will exclude things like ds-exos/numpy
  # with everything below; so we make sure to target only files and not directories
  # also this turns out to suppress too much content, like e.g. stuff in _static
  # and possibly other things that we don't want to exclude
  # so we don't exclude these, can still be helpful for incremental runs though
  # - "**/[a-z]*.[a-z]*"
  # convenience for authors - but DO NOT exclude .teacher
  # so the corrections can be built
  - "**/teacher/*"
  # generic exclusions
  - "**/trash/**/*"
  - "**/wip/*"
  - "**/.ipynb_checkpoints/*"
  - "**/.pytest_cache/*"

execute:
  execute_notebooks: cache
  exclude_patterns:
  # consider only filenames that start with an uppercase
    - "[a-z]**/[a-z]*"

parse:
  myst_enable_extensions:
    - html_image    # for raw <img> tags in markdown
    - dollarmath    # for mathjax
    - strikethrough

sphinx:
  config:
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py:percent
    html_theme_options:
      repository_url: https://github.com/flotpython/exos
      repository_branch: main
      path_to_docs: .
      use_issues_button: yes
      use_repository_button: yes
      use_download_button: yes
      home_page_in_toc: false
      toc_title: "TOC"

    html_favicon: media/flotpython-favicon.svg
    html_show_copyright: false
    html_extra_path:
      - media
      # would  be needed if we were to expose contents to jupyterlite
      # - lite
    html_static_path:
      - _static
    html_js_files:
      - my-book.js
    jupyterlite_dir: .
    # required as of 2024 May to get %matplotlib ipympl
    # to show up (at all, not even interactive) in the book output
    nb_ipywidgets_js:
        # Load RequireJS, used by the IPywidgets for dependency management
        "https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js":
            "integrity": "sha256-Ae2Vz/4ePdIu6ZyI/5ZGsYnb+m0JlOmKPjt6XZ9JJkA="
            "crossorigin": "anonymous"
        # Load IPywidgets bundle for embedding.
        "https://cdn.jsdelivr.net/npm/@jupyter-widgets/html-manager@*/dist/embed-amd.js":
            "data-jupyter-widgets-cdn": "https://cdn.jsdelivr.net/npm/"
            "crossorigin": "anonymous"

  extra_extensions:
    - jupyterlite_sphinx
