version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  # needed in a notebook to produce graphviz representations
  apt_packages:
    - graphviz
  jobs:
    pre_build:
      - jupyter-book config sphinx --toc $(pwd)/jb/python/_toc.yml --config $(pwd)/jb/_config.yml .
      # ideally we'd just like to have jupyter-book store its config in ./conf.py
      # for that purpose I have opened https://github.com/executablebooks/jupyter-book/pull/2074
      # in the meantime we just move the file ourselves
      - mv jb/conf.py .

sphinx:
  fail_on_warning: false
  builder: html
  # and so we no longer need this
  # configuration: jb/conf.py

python:
  install:
    - requirements: requirements.txt
    - requirements: jb/requirements-rtd.txt
